server:
  port: 84

spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置nacos地址
    sentinel:
      transport:
        dashboard: localhost:8080  #配置sentinel dashboard 地址
        port: 8719  #默认8719，假如被占用会自动从8719开始依次加1，直至找到未被占用的端口


#消费者将要去访问的微服务名称（注册成功进nacos的微服务提供者）
service-url:
  nacos-user-service: http://nacos-payment-provider


#激活sentinel对feign得支持
feign:
  sentinel:
    enabled: true
